education_menu = "xpath://a[text()='Education']"
free_courses = "//*[@id='menu-main-menu']//a[text()='Free Courses']"
courses_collection = "https://courses.ultimateqa.com/collections"
courses_link_locator = "xpath://*[@class='active' and @id='category-name']"
sign_in = "xpath://a[contains(text(),'Sign In')]"
sign_in_link= "https://courses.ultimateqa.com/users/sign_in"
search_input = "xpath://*[@name='q']"
product_title = "xpath://[@class='collections__heading']"
filter = "xpath://*[@class='product_sort_container']"
products_page= "xpath://div[@class='inventory_list']"
add_to_card = "xpath://*[@class='pricebar']"
card_button = "xpath://*[@name='Remove']"
total_price = "xpath://*[text()='Price Total']"